---
abstract: 'a Perl wrapper around F<libresolv>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::CChecker: 0
  Module::Build: 0
  Module::Build::Compat: 0
  Test::More: 0
configure_requires:
  ExtUtils::CChecker: 0
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-LibResolv
provides:
  Net::LibResolv:
    file: lib/Net/LibResolv.pm
    version: 0.02_001
requires:
  Exporter: 5.57
resources:
  license: http://dev.perl.org/licenses/
version: 0.02_001
